#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser/viewers
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
  export PDFVIEWER='open'
else
  export PDFVIEWER=zathura
  export TERMINAL=st-dvtm
  export BROWSER=browser
  export CHROMIUM_FLAGS="${CHROMIUM_FLAGS} --enable-print-preview"
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Go Paths
#
if (( $+commands[go] )); then
export GOPATH="$HOME/dev/go"
export GOOS=linux
export GOARCH=amd64
  if [[ -d "$GOPATH" ]]; then
    path=(
      "$GOPATH"/bin
      $path
    )
  fi
fi

[[ -f "$HOME/install/local/perlbrew/etc/bashrc" ]] && source "$HOME/install/local/perlbrew/etc/bashrc"

if [[ -d "$HOME/install/bin" ]]; then
  path=(
    "$HOME/install/bin"
    $path
  )
fi

if (( $+commands[cope_path] )); then
  path=(
    $(cope_path)
    $path
  )
fi

if [[ -d "$HOME/bin" ]]; then
  path=(
    "$HOME/bin"
    $path
  )
fi

if [[ -d "$HOME/install/share/man" ]]; then
  export MANPATH="$HOME/install/share/man":$MANPATH
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-g -i -M -R -S -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi



# Allow git to look for a repo across filesystems
# Used for my bind mounts
export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
