#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

[ -f /usr/bin/keychain ] && eval `keychain --eval -Q -q`
[ -f "$HOME/.keychain/$HOSTNAME-sh" ] && source "$HOME/.keychain/$HOSTNAME-sh" 2>/dev/null
[ -f "$HOME/.keychain/$HOSTNAME-sh-gpg" ] && source "$HOME/.keychain/$HOSTNAME-sh-gpg" 2>/dev/null

bindkey -M viins "$key_info[Control]R" zaw-history
bindkey -M filterselect "$key_info[Control]R" down-line-or-history
bindkey -M filterselect "$key_info[Control]S" up-line-or-history
bindkey -M viins "$key_info[Control]S" zaw-cs225-students

bindkey -M viins "^H" backward-delete-char

stty erase "^H"
