#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if (( $+commands[gpg-agent] )); then
    mkdir -p "/dev/shm/$USER/gpg" 
    [[ -f "/dev/shm/$USER/gpg/gpg-agent-info" ]] && source "/dev/shm/$USER/gpg/gpg-agent-info" &>/dev/null
    export GPG_AGENT_INFO
    if ! gpg-agent &>/dev/null; then
        gpg-agent --daemon --no-use-standard-socket --write-env-file "/dev/shm/$USER/gpg/gpg-agent-info" &>/dev/null
        [[ -f "/dev/shm/$USER/gpg/gpg-agent-info" ]] && source "/dev/shm/$USER/gpg/gpg-agent-info" &>/dev/null
    fi
fi

bindkey -M viins "$key_info[Control]R" zaw-history
bindkey -M filterselect "$key_info[Control]R" down-line-or-history
bindkey -M filterselect "$key_info[Control]S" up-line-or-history
bindkey -M viins "$key_info[Control]S" zaw-cs225-students


if [[ $TERM != "linux" ]]; then
    bindkey -M viins "^H" backward-delete-char
    bindkey -M viins "^?" delete-char
    stty erase "^H"
fi
